### ISSUE TITLE
Fonts are not loading for buttons

### ISSUE THREAD

**Issue by ixv** [urbit/indigo-react#28]
But are loading for header.

In Electron.
<img width="441" alt="Screen Shot 2019-10-29 at 11 57 47 AM" src="https://user-images.githubusercontent.com/4741759/67799834-61148b80-fa43-11e9-94aa-df7653c294c9.png">
<img width="775" alt="Screen Shot 2019-10-29 at 11 57 34 AM" src="https://user-images.githubusercontent.com/4741759/67799846-6671d600-fa43-11e9-8e01-d8dc3f46893a.png">

**Comment by nickbytes** [comment]
This should probably be updated. Right now, the `fontFamily` default is set to `inherit`. 

In the meantime @ixv, you could: 
- use a `<Span>` element inside the button I believe. The buttons were meant to be somewhat unassuming, since some end up being flex containers, with icons or groupings of different text. But I think you are right, there should be better defaults here.

I'm just curious: are you using any sort of minimal reset or normalize in electron? Maybe that's kind of a silly question. I usually at least do some border-box, antialiasing, etc etc. like [here](https://github.com/urbit/indigo-react/blob/master/example/src/App.js#L8).

**Comment by ixv** [comment]
Adding a Span did not work, but doing the reset from your link worked, thanks.
